---
- hosts: http1
  tasks:
  - name: Deploy the nginx container
    docker_container:
      image: nginx:stable
      name: nginx
      state: started
      auto_remove: true
      ports:
        - "8080:80"
      volumes:
        - "/var/www/html:/usr/share/nginx/html:ro"
