---

- name: "mediawiki database"
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{mediawiki_db_name}}"
    state: present

- name: "mediawiki user+privileges"
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{mediawiki_db_user}}"
    password: "{{mediawiki_db_password}}"
    priv: "{{mediawiki_db_name}}.*:ALL"
    host: "{{item}}"
    state: present
  with_items: "{{groups.apache}}"