---
# tasks file for Docker
- name: "Docker installation"
  package:
    name: "docker"
    state: "present"

- name: "Docker pip package install"
  pip:
    name: "docker"

- name: "Docker service activation"
  service:
    name: "docker"
    state: "started"
    enabled: yes

